# Generated by Django 5.1.6 on 2025-02-10 09:08

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphotomodel',
            name='photo',
            field=models.ImageField(upload_to=core.services.file_service.upload_post_photos),
        ),
    ]
