# Generated by Django 5.1.5 on 2025-01-27 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+380(50|66|95|99|63|73|93|67|67|68|77|96|97|98)\\d{7}$', 'Phone number must start with "+380" and then have 9 digits')]),
        ),
    ]
