# Generated by Django 5.1.5 on 2025-01-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(default='Lviv', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='country',
            field=models.CharField(default='Ukraine', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='nationality',
            field=models.CharField(default='Ukrainian', max_length=20),
            preserve_default=False,
        ),
    ]
