# Generated by Django 5.1.5 on 2025-01-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usermodel_options_profilemodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='birthday',
            field=models.DateField(default='2005-12-7'),
            preserve_default=False,
        ),
    ]
