# Generated by Django 5.1.5 on 2025-02-04 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profilemodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z0-9_-]{1,29}$', 'Name must start with upper case and contain maximum 30 letters')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='country',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z0-9_-]{1,29}$', 'Name must start with upper case and contain maximum 30 letters')]),
        ),
    ]
