# Generated by Django 5.1.5 on 2025-02-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profilemodel_city_alter_profilemodel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_logout',
            field=models.DateTimeField(null=True),
        ),
    ]
