# Generated by Django 5.1.6 on 2025-02-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_usermodel_last_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
