# Generated by Django 5.1.6 on 2025-02-05 18:05

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profilemodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.upload_user_photos),
        ),
    ]
